config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_items
  end
  namespace :todo_list do
    resources :todo_items do
      member do
        get :toggle_status
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  scope :completed, -> do
    where(completed: true)
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items
  def percent_complete
    return 0 if total_items == 0
    (100 * completed_items.to_f / total_items).round(1)
  end
  def total_items
    @todo_items ||=  todo_items.count
  end
  def completed_items
    @completed_items ||= todo_items.completed.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET todo_lists/1/todo_items
  def index
    @todo_items = @todo_list.todo_items
  end

  # GET todo_lists/1/todo_items/1
  def show
  end

  # GET todo_lists/1/todo_items/new
  def new
    @todo_item = @todo_list.todo_items.build
  end

  # GET todo_lists/1/todo_items/1/edit
  def edit
  end

  # POST todo_lists/1/todo_items
  def create
    @todo_item = @todo_list.todo_items.build(todo_item_params)

    if @todo_item.save
      redirect_to(@todo_item.todo_list)
    else
      render action: 'new'
    end
  end

  # PUT todo_lists/1/todo_items/1
  def update
    if @todo_item.update(todo_item_params)
      redirect_to(@todo_item.todo_list, notice: 'Todo item was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE todo_lists/1/todo_items/1
  def destroy
    @todo_item.destroy

    redirect_to todo_list_todo_items_url(@todo_list)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def todo_item_params
      params.require(:todo_item).permit(:description, :completed, :reminder, :completed_at, :todo_list_id)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    @todo_item = TodoItem.new
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        if @todo_list.reminder?
          TodoListMailer.with(todo_list: @todo_list).reminder_email.deliver
        end

        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # def send_email
  #   if @todo_list.email != nil
  #     UserMailer.with(todo_list: @todo_list).reminder_email.deliver_now
  #   else
  #     format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
  #     format.json { render :show, status: :ok, location: @todo_list }
  #   end
  # end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)

        if @todo_list.reminder?
          TodoListMailer.with(todo_list: @todo_list).reminder_email.deliver
        end

        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :email, :reminder)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
    <small>
        Created by : <a href="github.com/Shivansh1805">Shivansh Srivastava</a>
    </small>
    <nav>
    </nav>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Todo App","/" ,class: "navbar-brand" , id: "logo"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About" %></li>
        <li><%= link_to "Articles",todo_lists_path%></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Article" ,new_todo_list_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

  
   
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class='bg-light'>
    <div class = "container">
      <div class = "row">
        <div class = "col-md-10 col-lg-8 offset-md-1 offset-lg-2">
        <p id="notice"><%= notice %></p>
            <%= yield %>
        </div>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_with(model: [@todo_item.todo_list, @todo_item]) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='container'>
  <div class="field ">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>

  <div class="field">
    <%= f.label :completed_at %><br />
    <%= f.datetime_select :completed_at %>
  </div>

  <div class="actions mt-3 mb-2">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<h1>Editing todo_item</h1>

<%= render 'form' %>

<div align='center'>
<%= link_to 'Show', [@todo_item.todo_list, @todo_item] %> |
<%= link_to 'Back', todo_list_todo_items_path(@todo_item.todo_list) %>
</div>

app/views/todo_items/index.html.erb
<h1>Listing todo_items</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Completed</th>
    <th>Reminder</th>
    <th>Completed at</th>
    <th>Todo list</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todo_items.each do |todo_item| %>
  <tr>
    <td><%= todo_item.description %></td>
    <td><%= todo_item.completed %></td>
    <td><%= todo_item.reminder %></td>
    <td><%= todo_item.completed_at %></td>
    <td><%= todo_item.todo_list %></td>
    <td><%= link_to 'Show', [todo_item.todo_list, todo_item] %></td>
    <td><%= link_to 'Edit', edit_todo_list_todo_item_path(todo_item.todo_list, todo_item) %></td>
    <td><%= link_to 'Destroy', [todo_item.todo_list, todo_item], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Todo item', new_todo_list_todo_item_path(params[:todo_list_id]) %>

app/views/todo_items/new.html.erb
<h1>New todo_item</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_list_todo_items_path(@todo_item.todo_list) %>

app/views/todo_items/show.html.erb
<div class = "card mt-5">
  <p class='card-body'>
  <b>Description:</b>
  <%= @todo_item.description %>
  </p>

  <p class='card-body'>
  <b>Completed:</b>
  <%= @todo_item.completed %>
  </p>

  <p class='card-body'>
  <b>Reminder:</b>
  <%= @todo_item.reminder %>
  </p>

  <p class='card-body'>
  <b>Completed at:</b>
  <%= @todo_item.completed_at %>
  </p>

  <p class='card-body'> 
  <b>Todo list:</b>
  <%= @todo_item.todo_list %>
  </p>

  <div align='center'>
    <%= link_to 'Edit', edit_todo_list_todo_item_path(@todo_item.todo_list, @todo_item) %> |
    <%= link_to 'Back', todo_list_todo_items_path(@todo_item.todo_list) %>
  </div>

</div>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="control-label col-sm-2">
    <%= form.label :title %>
    </div>
    <div class="col-sm-8">
        <%= form.text_field :title , class:"form-control",placeholder:"Title ", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= form.label :email %>
    </div>
    <div class="col-sm-8">
        <%= form.email_field :email , rows: 10 ,class: "form-control", placeholder: "Email" %>
        <div mt-5>
        <%= form.label :reminder %><br />
        <%= form.check_box :reminder %>
        </div>
    </div>
  </div>





  <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
          <%= form.submit class:"btn btn-primary btn-lg"%>
      </div>
  </div>

<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<div class = "card mt-5">
  <div class = "card-header d-flex justify-content-between">
    <h3><b>Todo Lists</b></h3>
    <%= link_to 'New Todo List', new_todo_list_path, class:'btn btn-info btn-sm'%>
  </div>

  <ul class='list-group'>
    <% @todo_lists.each do |todo_list| %>

      <li class='list-group-item bg-light' >
              <div class="d-flex justify-content-between">
                <span>
                  <b color=blue><%= todo_list.title %></b>
                </span>
                <div class="article-action">
                <%= link_to 'Show', todo_list, class:'btn btn-success btn-xs'%>
                <%= link_to 'Edit', edit_todo_list_path(todo_list), class:'btn btn-primary btn-xs'%>
                <%= link_to 'Delete', [todo_list], class:'btn btn-danger btn-xs',method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              </div>
        </li>
    <% end %>
  </ul>
</div>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>


<%= render 'form', todo_list: @todo_list %>

<div align="center">
<p mt-5><%= link_to 'Back', todo_lists_path %></p>
</div>

app/views/todo_lists/show.html.erb
<div class = "card mt-5">
    <div class = "card-header d-flex justify-content-between">
      <div>
        <h5><b><%= @todo_list.title %></b></h5>
        <p class='text-secondary'><small><%= @todo_list.percent_complete %> % Complete (<%= @todo_list.completed_items%>/<%= @todo_list.total_items%> Todo Items)</small></p>
      </div>
      <div>
        <%= link_to 'Add new Todo', new_todo_list_todo_item_path(@todo_list), class:'btn btn-primary '%>
      </div>
    </div>
    <div class="card-body">
      <div class="progress mb-4">
        <div class="progress-bar bf-info" role="progressbar" style="width: <%= @todo_list.percent_complete %>%" aria-valuenow="<%=@todo_list.percent_complete %>" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <ul class='list-group'>
          <% @todo_list.todo_items.each do |todo_item| %>
            <% if todo_item.completed == false %>
              <li class='list-group-item'>
                <div class="d-flex justify-content-between">
                  <span>
                    <%= todo_item.description %>
                  </span>
                  <%= link_to 'Edit', edit_todo_list_todo_item_path(todo_item.todo_list, todo_item), class:'btn btn-info' %>
                </div>
              </li>
            <%end%>
          <% end %> 

          <% @todo_list.todo_items.each do |todo_item| %>
            <% if todo_item.completed != false %>
              <li class='list-group-item bg-light' >
                <div class="d-flex justify-content-between">
                  <span class='text-muted'>
                    <em><%= todo_item.description %></em> 
                  </span>
                  <%= link_to 'Edit', edit_todo_list_todo_item_path(todo_item.todo_list, todo_item), class:'btn btn-dark' %>
                </div>
              </li>
              <%end%>
          <% end %> 
      </ul>
    </div>
</div>